<a href="https://colab.research.google.com/github/sbborusu/git-learning/blob/main/00_NumPy_Crash_Course_Overview.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Crash Course

In [2]:
import numpy as np

In [3]:
np.__version__

'2.0.2'

## Creating Arrays

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [7]:
arr = np.array(my_list)

In [8]:
arr

array([0, 1, 2, 3, 4, 5])

In [9]:
type(arr)

numpy.ndarray

In [ ]:
type(my_list)

list

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [10]:
np.arange(3.0)

array([0., 1., 2.])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
np.arange(20,10)

array([], dtype=int64)

In [15]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [16]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [17]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [ ]:
np.arange(30,20)  # 1st arg always be < then 2nd arg

In [18]:
b = np.arange(-30,20)
b

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [19]:
np.arange(10,10)

array([], dtype=int64)

In [20]:
np.arange(-20,20)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,
        19])

In [21]:
np.arange(10,30,5)  # 10- starting from 30- end point 5 - step count

array([10, 15, 20, 25])

In [22]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [23]:
np.arange(10,30,5,1)

TypeError: Cannot interpret '1' as a data type

In [24]:
b1 = np.zeros(2) #parameter tunning
b1

array([0., 0.])

In [25]:
np.zeros(5,dtype=int) #hyperparameter tunning

array([0, 0, 0, 0, 0])

In [26]:
zero = np.zeros((2,2))
zero

array([[0., 0.],
       [0., 0.]])

In [27]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [30]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [32]:
np.zeros((5,10)) # bydefaul 1arge -- will give row & 2nd arg - columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
n = (5,7)
print(type(n))
n1 = (6,8)
print(np.zeros(n)) # parameter tunnin g
#print(np.zeros(n1,dtype=int)) ## hypyerparameter tunning

<class 'tuple'>
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [34]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [35]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [36]:
np.ones(4)

array([1., 1., 1., 1.])

In [37]:
n

(5, 7)

In [38]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [40]:
print(np.ones((5,4),dtype=int)) # by default 5- rows & 4 - columns
print(np.ones((2,5,4), dtype=int))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [41]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [42]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
np.ones((6,10),dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [44]:
np.twos((2,4))

AttributeError: module 'numpy' has no attribute 'twos'

In [45]:
np.three((2,4))

AttributeError: module 'numpy' has no attribute 'three'

# please add new notebook & compare with np & *

![image.png](attachment:a502943e-e1e4-4863-b86f-3a46f74e6840.png)

In [ ]:
>>> from numpy import *
>>> arange(3)

In [ ]:
range(12)
list(range(12))

In [ ]:
y = list(range(12))
y

In [ ]:
np.

In [ ]:
>>> from numpy import *
>>> zeros(5)

In [ ]:
np.threes((3,2))

In [ ]:
rand(3,2)
random.rand(3,2)

In [ ]:
np.random.rand(4)

In [ ]:
np.rand(4)

In [ ]:
np.random.rand(2,4)

In [ ]:
np.random.randint(2,20) # 2nd argument is exlusive

In [ ]:
np.random.randint(0,2)

In [ ]:
np.random.randint(1,10,4)

In [ ]:
np.random.randint(1,3,5)

In [ ]:
np.random.randint(30,20,10)

In [ ]:
np.random.randint(1)

In [ ]:
np.random.randint(5,9)  #GET THE VALUE <=1 & >=5

In [ ]:
np.random.randint(10,21,3)

In [ ]:
np.random.randint(1,12,10)

In [ ]:
np.random.randint(10,40,(10,10)) #generre the element 10 -30 with 4*4 mtri

In [ ]:
b = np.random.randint(10,20,(5,4))
b

In [ ]:
b[:]

In [ ]:
b[0:2]

In [ ]:
b

In [ ]:
b[0:-1]

In [ ]:
b

In [ ]:
b[0,2]

In [ ]:
np.random.randint(10,20,(4,4))

## Operations

In [ ]:
a = np.random.randint(10,20,5)
a

In [ ]:
arr

In [ ]:
arr2 = np.random.randint(0,100,(10,10))

In [ ]:
arr2

In [ ]:
arr

In [ ]:
arr[:]

In [ ]:
arr[:4]

In [ ]:
arr2[:]

In [ ]:
arr2[0:5]

In [ ]:
arr2

In [ ]:
arr2[1,5]

In [ ]:
arr2

In [ ]:
arr2[-5,5]

In [ ]:
arr2[-5,-5]

In [ ]:
arr2

In [ ]:
arr2[-5,-5]

In [ ]:
arr2

In [ ]:
arr2[-1,-2]

In [ ]:
arr2

In [ ]:
arr2[::-1]

In [ ]:
arr2

In [ ]:
arr2[::-2]

In [ ]:
arr2

In [ ]:
arr2[::-3]

In [ ]:
arr

In [ ]:
arr.max()

In [ ]:
arr.min()

In [ ]:
arr

In [ ]:
arr.mean()

In [ ]:
arr.median()

In [ ]:
>>> from numpy import *
>>> a = array([1,2,3,4,9])
>>> median(a)

In [ ]:
arr

In [ ]:
arr.reshape(2,3)

In [ ]:
arr.reshape(6,1)

In [ ]:
arr.reshape(1,6)

In [ ]:
arr.reshape(1,6)

In [ ]:
arr

In [ ]:
arr.reshape(1,5)

In [ ]:
arr.reshape(3,2,order='C')

In [ ]:
arr.reshape(3,2,order='F')

In [ ]:
arr.reshape(3,2,order='A')

In [ ]:
arr.reshape(3,2,order='K')

In [ ]:
arr

In [ ]:
arr.reshape(2,3)

In [ ]:
arr.reshape(1,4)

In [ ]:
arr.reshape(1,6)

In [ ]:
arr.reshape(6,1)

In [ ]:
arr.reshape(2,6)

In [ ]:
arr.reshape(3,3)

In [ ]:
arr

In [ ]:
arr.reshape(3,2)

## Indexing

In [ ]:
mat = np.arange(0,100).reshape(10,10)

In [ ]:
mat

In [ ]:
row = 4
col = 5

In [ ]:
col

In [ ]:
row

In [ ]:
mat

In [ ]:
mat[row,col]

In [ ]:
mat[4,5]

In [ ]:
mat

In [ ]:
mat[:]

In [ ]:
col = 6

In [ ]:
mat

In [ ]:
# With Slices
mat[:,col]

In [ ]:
mat

In [ ]:
mat[row,:]

In [ ]:
mat

In [ ]:
mat[:,col]

In [ ]:
mat[:col]

In [ ]:
row

In [ ]:
mat

In [ ]:
mat[:row]

In [ ]:
mat[row:]

In [ ]:
mat[:]

In [ ]:
mat[:,8]

In [ ]:
mat

In [ ]:
mat[:,-1]

In [ ]:
mat

In [ ]:
row

In [ ]:
col

In [ ]:
mat[:,col]

In [ ]:
mat

In [ ]:
mat[1,4]

In [ ]:
mat

In [ ]:
mat[1:4]

In [ ]:
mat

In [ ]:
mat[3:-3]

In [ ]:
mat

In [ ]:
mat[0]

In [ ]:
mat[6]

In [ ]:
mat

In [ ]:
mat[6:]

In [ ]:
mat[:6]

In [ ]:
mat

In [ ]:
mat[5:7]

In [ ]:
mat

In [ ]:
mat[0:10]

In [ ]:
mat[0:10:3]

In [ ]:
mat[0:10]

In [ ]:
mat[0:10:3]

In [ ]:
mat

In [ ]:
mat[4:]

In [ ]:
mat

In [ ]:
mat[:4]

In [ ]:
mat

In [ ]:
mat[::-1]

In [ ]:
mat[::-2]

In [ ]:
mat

In [ ]:
mat[::-3]

In [ ]:
mat

In [ ]:
mat[::-5]

In [ ]:
mat

In [ ]:
mat[2:6]

In [ ]:
mat

In [ ]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicates only column parts

In [ ]:
mat

In [ ]:
mat[0,1]

In [ ]:
mat[1,6]

In [ ]:
mat

In [ ]:
mat[1:6]

In [ ]:
mat[1:]

In [ ]:
mat

In [ ]:
mat[:6]

In [ ]:
mat[0:1]

In [ ]:
mat

In [ ]:
mat[3:5]

In [ ]:
mat[3,5]

In [ ]:
mat

In [ ]:
mat[1:2,2:4]

In [ ]:
mat

In [ ]:
mat[2:3,2:3]

In [ ]:
mat

In [ ]:
mat[3:5,2:4,]

In [ ]:
mat

In [ ]:
mat[2:3,4:5]

## Masking

In [ ]:
mat # we also called as filter

In [ ]:
id(mat)

In [ ]:
mat

In [ ]:
mat < 50

In [ ]:
mat > 50

In [ ]:
mat == 50

In [ ]:
mat[mat==50]

In [ ]:
a1 = mat[mat<50]
a1

In [ ]:
mat

In [ ]:
a2 = mat[mat>50]
a2

In [ ]:
a3 = mat[mat>=50]
a3

In [ ]:
a4 = mat[mat==50]
a4

In [ ]:
mat>50

In [ ]:
a1

In [ ]:
a2